# Permalinks
permalink:        /:title

# Setup
title:            TakaSoft
tagline:          Making awesome software
description:      Making awesome software
url:              
baseurl:          
headline:         My name is Takao Shibamoto, a computer engineering student at Iowa State University. 

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
