# Permalinks
permalink:        /:title

# Setup
title:            TakaSoft
tagline:          Making awesome software
description:      Making awesome software
url:              
baseurl:          https://takasoft.github.io
rawurl:           https://github.com/takasoft/takasoft.github.io/raw/master
# Add this and create headline.html in _includes directory
headline: true         
# Add your google_analytics ID if you need it
# google_analytics: 

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
