# Permalinks
permalink:        /blog/:title

# Setup
title:            TakaSoft
tagline:          
description:      A blog by Takao Shibamoto, a Computer Engineering student at Iowa State.
url:              https://takasoft.github.io
baseurl:          
rawurl:           
# Add this and create headline.html in _includes directory
headline: true         
# Add your google_analytics ID if you need it
# google_analytics: 

# Pagination number
paginate:         10
paginate_path: "/blog/:num/"
